$ANSIBLE_VAULT;1.1;AES256
65633230663030363666396435613664353835653934633064663036353266646434363766393836
3861613262663138636239343635366666326638366162310a646665663731346464626462636239
61646366363834376666303164613937653833326337333661393562393938303263643535393939
3537373762366131620a616333613131363731643137356432376635653736333437383733616532
6361
