github_org: "TestingJDA"
min_runners: 2
docker_runner_image: "ghcr.io/actions/runner:latest"
runner_image_name: "github-ephemeral-runner:latest"
github_token: "{{ vault_github_token }}"
github_user: "josedanielacevedovass"
vault_github_token: "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"
github_account: "josedanielacevedovass"